#!/usr/bin/bash
. ./random_aya --source-only
. ./random_hadith --source-only

send_random_ayat() {
    local data_ayat=$(fetch_random_ayat)
    local surah=$(echo "$data_ayat" | jq -r '.data.surah.name')
    local text=$(echo "$data_ayat" | jq -r '.data.text')

    if [ -z "$surah" ] || [ -z "$text" ]; then
        echo "Failed to extract Surah or Text from the API response"
        exit 1
    fi
    # echo surah "$surah" text "$text"

    notify-send "$surah" "$text"
}


send_random_hadith() {
    local data_hadith=$(fetch_random_hadith)
    local hadith=$(echo "$data_hadith" | jq -r '.hadith[1].body')
    local sliced_hadith="${hadith:4:-4}" # Data is wrapped between <p> tags and that doesn't get rendered.
    # echo hadith $hadith
    notify-send "حديث شريف" "$sliced_hadith"
}
# Set up environment variables for notify-send to work with cronjobs.
userid=$(id -u)
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$userid/bus"
export DISPLAY=:0.0
export XAUTHORITY="/home/$LOGNAME/.Xauthority"

# Call the functions to fetch and display notifications
send_random_ayat
sleep 10
send_random_hadith
